title: The Turing Way                         # The title of the book
author: The Turing Way Community                        # The author of the book to be placed in the footer
copyright: '2020'                     # Copyright year to be placed in the footer
logo: ./figures/logo.png                            # A path to the book logo


html:
  favicon: ./figures/favicon-32x32.png                       # A path to a favicon image
  navbar_footer_text: Visit our <a href="https://github.com/alan-turing-institute/the-turing-way">GitHub
    Repository</a> <div> This book is powered by <a href="https://jupyterbook.org">Jupyter
    Book</a> </div> # Will be displayed underneath the left navigation bar.


  use_repository_button: true       # Whether to add a link to your repository button
  use_issues_button: true           # Whether to add an "open an issue" button


#######################################################################################
repository:
  url: https://github.com/alan-turing-institute/the-turing-way                         # The URL to your book's repository
  path_to_book: book/website                  # A path to your book's folder, relative to the repository root
  branch: master                      # Which branch of the repository should be used when creating links

